### ISSUE TITLE
Feature Request: Customer, Project or Activity specific rounding and multipliers

### ISSUE THREAD

**Issue by erroneousio** [kevinpapst/kimai2#1003]
**Is your feature request related to a problem? Please describe.**
It is not directly related to a problem, more of a nice to have.

**Describe the solution you'd like**
Currently, it is possible to configure rounding and multipliers on a per day basis. I would like the ability to further configure rounding and multipliers to select specific customers, projects, or activities. I have a few activities where I would like rounding to be disabled as the time is billed per minute.

Currently, my `local.yaml` looks like this:
```yaml
kimai:
    timesheet:
        mode: duration_only
        rates:
            weekend:
                days: ['saturday', 'sunday']
                factor: 1.5
            weekday:
                days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']
                factor: 1
        rounding:
            weekend:
                days: ['saturday', 'sunday']
                begin: 1
                end: 1
                duration: 60
                mode: default 
            weekday:
                days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']
                begin: 1
                end: 1
                duration: 15
                mode: default
```

I would like to be able to select specific customers, projects and activities to use custom rounding, for example:
```yaml
kimai:
    timesheet:
        mode: duration_only
        rates:
            priority:
                customer: ['Customer 1', 'Customer 7']
                factor: 1.25
            weekend:
                days: ['saturday', 'sunday']
                factor: 1.5
            default:
                factor: 1
        rounding:
            lotsatime:
                customer: ['Customer 1']
                project: ['Project 5']
                begin: 1
                end: 1
                duration: 1
            printers:
                activity: ['Activity 1', 'Activity 3']
                begin: 1
                end: 1
                duration: 1
            weekend:
                days: ['saturday', 'sunday']
                begin: 1
                end: 1
                duration: 60
            default:
                begin: 1
                end: 1
                duration: 15
                mode: default
```

Rates are additive, so if Customer 1 had some work done on Sunday, it'd be a factor of 1.75. Or possibly there would be an option to specify if you wish for it to add all matching rates or be a stand alone rate.

Rounding would select the best matching with a similar priority to how the rate calculation is done currently. Under `lotsatime` any time entered on Project 5 under Customer 1 would be per minute. Under `printers` any time added that is Activity 1 or Activity 3 under any project or customer would also be logged per minute.

**Additional context**
For most of my time entries, rounding to a 15 minute incremented duration is fine. However, I have a few tasks that require 1 minute billing and would like log them in Kimai without the rounding currently configured (per day) impacting the time I enter.
