### ISSUE TITLE
Prevent overlapping times for one user?

### ISSUE THREAD

**Issue by juppin** [kevinpapst/kimai2#1184]
**Is your feature request related to a problem? Please describe.**
I have some users that do time tracking and sometimes they have entered overlapping times...
This is very time consuming for me to ask the workers to change there work times to not overlapp and sometimes they don´t remember there correct times if it was some time ago.

**Describe the solution you'd like**
Can we prevent the user to enter work times that overlapp with a setting like:
```
kimai:
    timesheet:
        overlapping:
            allow_for_user: false
```

**Describe alternatives you've considered**
Instruct the workers to recheck the entered times twice :-)
