### ISSUE TITLE
500 error on system-config "Unknown config: default.mode"

### ISSUE THREAD

**Issue by github-luckow-org** [kevinpapst/kimai2#1290]
**Describe the bug**
500 error when i try to go to the settings page.
I have no idea when and why. A fresh installation of kimai (i use it on cloudron.io) does not produce this bug. 

**To Reproduce**
1. Go to /en/admin/system-config/
2. Something is wrong 

**Logfile**
```
request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Unknown config: default.mode" at /app/code/src/Configuration/StringAccessibleConfigTrait.php line 111 {"exception":"[object] (InvalidArgumentException(code: 0): Unknown config: default.mode at /app/code/src/Configuration/StringAccessibleConfigTrait.php:111)"} []
```
**Screenshots**

**Additional context**
 - latest Kimai version (and before)
 - PHP 7.2.10

**Comment by kevinpapst** [comment]
Never seen this. You need to provide more information.
Is this a fresh install or an updated version?
Do you have a local.yaml?
Do you use plugins?

**Comment by github-luckow-org** [comment]
It's an updated version (imho since 3 or 4 versions). Have no clue, when this bug happened the first time. No plugins and the following local.yaml:

kimai:
    timesheet:
        rounding:
            weekend:
                days: ['saturday','sunday']
                begin: 1
                end: 1
                duration: 60
                mode: closest

**Comment by github-luckow-org** [comment]
After i removed the content of the local.yaml file (and did a bin/console cache:clear --env=prod) everything works fine. It seems there is a problem with the "TABS"

```yaml
kimai:
    timesheet:
        rounding:
            weekend:
                days: ['saturday','sunday']
                begin: 1
                end: 1
                duration: 60
                mode: closest
```
And the best: i could reproduce the behavior on a fresh installation. I copied the content of the yaml to the fresh installation bin/console ... and boom 500er. 
crazy :)
