### ISSUE TITLE
Multiple teamleads

### ISSUE THREAD

**Issue by davidus05** [kevinpapst/kimai2#1292]
I really like Kimai so far. Now I had a feature request from my users that every user in a team should see the timesheet of other users in his team.
We have four teams hosted on our Kimai platform.

What I want to do:
User "Franz" in Team A should see:
- the timesheet of user "Markus" in Team A
- but not the timesheet of user "Hans" in Team B

What is the correct permission for this?

In the loal.yaml file where I want to overwrite the permissions I wanted to set a thing like:
```
kimai:
    permissions:
        roles:
            ROLE_USER: ['view_other_timesheet']
```
... but when I set this the user can also see the timesheets of users in other teams. Is there no permission (which the teamleader has, too) like: view_timesheet_team? Which permission does the teamleader have? The teamleader does only see the timesheets of his team ...
