### ISSUE TITLE
API: Modify endpoint to get user details with timesheet

### ISSUE THREAD

**Issue by HonzaKopecky** [kevinpapst/kimai2#1535]
**Is your feature request related to a problem? Please describe.**
I am using the `/api/timesheets?user=all&full=true` endpoint to retrieve all timesheet entries for all users. I would like to include user details in the response.

**Describe the solution you'd like**
I was going to propose you could just change the configuration file `config/serializer/App/Entity.Timesheet.yml` to include user details when the full parameter is present. But then I realized not everyone might want user details in the response.

**Describe alternatives you've considered**
I tried to figure out how do I configure the way the data is serialized in my local environment. I created the following configuration in my `local.yaml`:

```
jms_serializer:
    metadata:
        directories:
            FOSUB_local:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/../config/packages/local/FOSUserBundle"
            App_local:
                namespace_prefix: "App"
                path: "%kernel.root_dir%/../config/packages/local/App"
```

But the problem is that this overwrites the configuration for all entities so if I just create a config file for the Timesheet entity, the API breaks down because there is no config for the other entities.

**The question**
Is there any way to modify the existing endpoint locally? I think I could create another endpoint but I still don't see a way how would I modify the serialization configuration just for my own install.
