### ISSUE TITLE
LDAP AD Configuration

### ISSUE THREAD

**Issue by Cookiedelu** [kevinpapst/kimai2#1594]
Hello,

I've been working on the LDAP setup for several hours without success with Active Directory.
I have deployed the stable branch and have followed the instructions to complete the LDAP configuration by adding the block in the file local.yaml (then reload the config and re-apply the permissions).

Please find below the content of the file:
```
kimai:
    ldap:
        connection:
            host: 192.168.0.2
            username: account@domain.local
            password: password
            accountDomainName: domain.local
            accountDomainNameShort: DOMAIN
            accountFilterFormat: (&(objectClass=Person)(sAMAccountName=%s))
        user:
            baseDn: dc=domain,dc=local
            filter: (&(objectClass=Person))
            usernameAttribute: samaccountname
            attributesFilter: (objectClass=Person)
            attributes:
                - { ldap_attr: mail, user_method: setEmail }
                - { ldap_attr: displayname, user_method: setAlias }
                - { ldap_attr: samaccountname,  user_method: setUsername }
        #role:
            #baseDn: dc=domain,dc=local
            #filter: (&(objectClass=group))
            #groups:
                #- { ldap_value: Leads, role: ROLE_TEAMLEAD }
                #- { ldap_value: Sysadmins, role: ROLE_SUPER_ADMIN }
                #- { ldap_value: Users, role: ROLE_USER }
```
I can see that authentication to the Active Directory server is successful and that the user requested for authentication is found. I get the message "Invalid credentials".

How can I get more details or more logs to understand the behavior ?

Thank you !
