### ISSUE TITLE
unable to export to pdf invoice

### ISSUE THREAD

**Issue by heeen** [kevinpapst/kimai2#1619]
**Describe the bug**
twig exports named /var/invoices/*.pdf.twig are not listed in the invoice document selection

**To Reproduce**
1. add template in var/invoices/foo.html.twig, copying existing template
2. observe you can select it in invoice edit menu
3. observe you can rename it and see the changed name
4. rename it to foo.pdf.twig
5. observe that the template disappears from the menu

**Logfile**
nothing interesting in the logfile

**Screenshots**
as described

**Desktop/Smartphone**
Please complete the following information if this seems to be a frontend issue:
 - Device: [e.g. iPhone6s]

**Additional context**
 - Kimai version 1.8, docker-compose:
```
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p...
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3 

  nginx:
    build: compose
    ports:
      - 8001:80
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - kimai
    volumes:
      - public:/opt/kimai/public
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1 
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3 

  kimai:
    image: kimai/kimai2:fpm-alpine-1.8-prod
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=,localhost,nginx
      - ADMINMAIL=
      - ADMINPASS=
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://nginx || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  postfix:
    image: catatnight/postfix
    environment:
      maildomain: 
      smtp_user: kimai:kimai
    restart: unless-stopped
    restart: always

volumes:
    var:
    public:
```
