### ISSUE TITLE
Bad display of the dots

### ISSUE THREAD

**Issue by Joezzef** [kevinpapst/kimai2#1978]
Repost from [tobybatch git issue 158](https://github.com/tobybatch/kimai2/issues/158)

**Describe the bug**
I have tried to use the image 1.10.2 and I have weird display of the dots in the different list (customer, projects...) as shown below :
![dot_bad_display_image_v1 10 2](https://user-images.githubusercontent.com/60783146/93179591-2c322580-f736-11ea-9f2a-31672b987faa.png)

Same behavior on Chrome and Edge. 

This was not the case in v1.8.

**To Reproduce**

1. Modify the image selected in the docker-compose file from 1.8 to 1.10.2 
2. Start everything with the docker-compose up command. 
3. Create a customer
4. Check the display in the list. 

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Chrome : 85.0.4183.102 (but same behavior on my tests on Edge)
 - Docker version: 18.09.7
 - Docker compose version: 1.20.0

**Command used to run the container**
 - sudo docker-compose up 

**Docker compose file (with passwords redacted)**

```yaml
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -pchangemeplease ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  nginx:
    build: compose
    ports:
      - 8001:80
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - kimai
    volumes:
      - public:/opt/kimai/public
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:fpm-alpine-1.10.2-prod
    environment:
      - APP_ENV=prod
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai
      - TRUSTED_HOSTS=nginx,localhost, (my ip adress removed)
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://nginx || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  postfix:
    image: catatnight/postfix
    environment:
      maildomain: neontribe.co.uk
      smtp_user: kimai:kimai
    restart: unless-stopped
    restart: always

volumes:
    var:
    public:
```

**Additional information : **
For now, not an expert of docker but I am working to improve :)

Thanks in advance.

J.
