### ISSUE TITLE
LDAP Group cannot be configured for FreeIPA

### ISSUE THREAD

**Issue by NikoGrano** [kevinpapst/kimai2#2149]
**Describe the bug**
LDAP Groups will not work with FreeIPA due full path required for member.

**Current Configuration**

```yaml
        # Only relative to this issue has been copied.
        user:
            baseDn: cn=accounts,dc=example,dc=com
            usernameAttribute: uid
        role:
            baseDn: cn=groups,cn=accounts,dc=example,dc=com
            filter: (&(objectClass=groupOfNames))
            nameAttribute: cn
            userDnAttribute: member
```

**What Happens**
Instead of providing useless logs about this, Ill just tell here what I found out by debugging the instance.

1. Authentication for LDAP is successful.
2. Groups are queried from LDAP with following arguments:
```yaml
            baseDN: cn=groups,cn=accounts,dc=example,dc=com
            filter: (&(&(objectClass=groupOfNames))(member=username))
```
3. Query results empty.

**What went Wrong**

For FreeIPA, you cannot just provide member as `cn`. I could add config `userDnAttribute: member=uid`. However, this doesn't help much. You need to also provide full DN for the user. Example:

**Hack Fix**

Currently I'm just using additional variable to inject full DN to user argument here on line 160.
https://github.com/kevinpapst/kimai2/blob/4a945253209bf3b1d1257c1f6bf7362a23474844/src/Ldap/LdapManager.php#L158-L162
```php
sprintf(
            '(&%s(%s=%s%s))',
            $filter,
            $roleParameter['userDnAttribute'],
            ldap_escape($dn, '', LDAP_ESCAPE_FILTER),
            $roleParameter['userBaseDn']
);
            // $roleParameter['userBaseDn'] = ','.$userParameter['baseDn];
```

This change modifies query to following.
```yaml
            baseDN: cn=groups,cn=accounts,dc=example,dc=com
            filter: (&(&(objectClass=groupOfNames))(member=uid=username,cn=users,cn=accounts,dc=example,dc=com))
```

I find this way **pure hack** and I think there is better ways to fix this issue. Expecting this is a issue, not a configuration mistake on my end.

**Additional context**
 - Kimai version:  1.11.1
 - PHP version: 7.4
