### ISSUE TITLE
Change default language/timezone

### ISSUE THREAD

**Issue by ctpntn** [kevinpapst/kimai2#2240]
**Describe the bug**
I've been using this configuration in local.yaml:
```
kimai:
    defaults:
        user:
            timezone: Europe/Rome
            language: it
```

but users language is in English.
Should the new default values be available for existing users too?
