### ISSUE TITLE
make:migration command drop table kimai2_sessions

### ISSUE THREAD

**Issue by iAdil** [kevinpapst/kimai2#2297]
**Describe the bug**
"bin/console make:migration" command create a migration file with plugins migration tables drop and kimai2_sessions table drop
```
        $this->addSql('DROP TABLE bundle_migration_kiosk');
        $this->addSql('DROP TABLE bundle_migration_metafields');
        $this->addSql('DROP TABLE kimai2_sessions');
```
What is the right way to create a migration file?

**Additional context**
 - Kimai version: Kimai 2 - 1.12 stable (Ayumi) 
 - PHP version: 7.3

**Comment by kevinpapst** [comment]
That is the right way. A migration file is not always meant to work out of the box and should be fine-tuned manually.
Remove the commands that don't belong to your changes.

You can also try to add the `schema_filter` line in `config/packages/doctrine.yaml`:
```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                schema_filter: ~^(?!(bundle_migration_|kimai2_sessions))~
```

I guess I will it add it to the Core if it works properly.
