### ISSUE TITLE
Users loose admin permissions al the time 

### ISSUE THREAD

**Issue by bash-stack** [kevinpapst/kimai2#2321]
**Describe the bug**
the 2 "non-default" users always see their permissions dropped,
that is extremely annoying since entered data my be lost due to CSRF-Token/Session expired

as a countermeasure a cronjob kicks in ( every 2 minutes, wastes endless context switches)
`docker exec -t the.kimai.thingy su -s /bin/bash -c '$(ls /var/www/kimai2*/bin/console|sort -n|tail -n1)  fos:user:promote the-uer-name ROLE_ADMIN' &>/tmp/kimai.elevate.log`

**To Reproduce**
1. create admin user in 1.9
2. let it run a bit
3. have the complains

**Logfile**
```
nothing appears in prod.log
```

**Additional context**
 - Kimai version: 1.9
 - PHP version: 7.4
 - Device: ( does not matter, happens even when logged out
 - Browser:( does not matter , happens in system)

**Comment by kevinpapst** [comment]
Nope, 100% sure that this is not a Kimai bug. Must be some kind of weird environment issue. I don't use docker and don't give support for problems that arise from its usage.
Also: 1.13 will be released this weekend, its time to upgrade your Kimai 😁

**Comment by bash-stack** [comment]
well , it changes in sql  ..  nothing else acceses the db .. so it's not "magiccally chaging by itself"

**Comment by kevinpapst** [comment]
I believe that you see the issue.  But I have never heard of such a problem and Kimai is used daily by thousands of users... so it must be something that is influenced by the setup/environment. And I cannot debug that.

Are you sure that is it missing in the database and not session timeout that causes this weird issue?
Is it always the same time period until it happens? 
Can it be triggered by multiple concurrent requests (fast opening many Kimai tabs)?

**Comment by bash-stack** [comment]
might it be that ldap overwrites ?

**Comment by kevinpapst** [comment]
Aha. Is that a case of RTFM? 😁 
https://www.kimai.org/documentation/ldap.html#role-changes-will-be-overwritten

**Comment by bash-stack** [comment]
( but ldap group sync seems not working propely, will check again after upgrade)

**Comment by bash-stack** [comment]
okay, i remember what happened:

manual says :

`The rule is: either manage all roles in Kimai or in LDAP, mixing is not possible.`

And enablng any group function disables login (...) , so the idea was "only 2 admins, , can be done manually due to the manual"

maybe the hint should be "using LDAP will disable other group functions "

**Comment by kevinpapst** [comment]
I don't understand the issue. Maybe its better to completely manage these two admins in Kimai?

**Comment by bash-stack** [comment]
bro , thats what i tried .. ( new report in pipe )

**Comment by kevinpapst** [comment]
No, you don't. You are trying to change users that are connected via LDAP.
Managing means creating the users inside Kimai with a different username, email - so they don't get attached to LDAP afterwards.

**Comment by bash-stack** [comment]
as already stated under #2324 it was a struggle to bind univention to kimai but worked with:

```
#monolog:
#    handlers:
#        main:
#            action_level: debug

security:
    providers:
        chain_provider:
            chain:
                providers: [kimai_ldap]
    firewalls:
        secured_area:
            kimai_ldap: ~

kimai:

##### password rest disabled due to ldap upstream ( see manual)
    permissions:
        roles:
            ROLE_USER: ['!password_own_profile']
            ROLE_TEAMLEAD: ['!password_own_profile']
            ROLE_ADMIN: ['!password_own_profile']
##### password rest disabled due to ldap upstream ( see manual)
    user:
        registration: false
        password_reset: false
    ldap:
        connection:
            host: ldap.somedomain.de
            # Default port for your LDAP port server
            # default: 389
            port: 63636
            useSsl: true
            username: cn=kimai_somedomain_systems,cn=computers,dc=somedomain,dc=de
            password: TheLDAPpasswordOFtheUSERthatKIMAIusesTObind
            accountFilterFormat: (&(objectClass=posixAccount)(uid=%s))
            bindRequiresDn: true
            allowEmptyPassword: false
            tryUsernameSplit: true
        user:
            baseDn:  dc=somedomain, dc=de
            usernameAttribute: uid
            filter: (&(objectClass=posixAccount))
            attributes:
                - { ldap_attr: uid, user_method: setUsername }
                - { ldap_attr: mailprimaryaddress, user_method: setEmail }
                - { ldap_attr: displayname, user_method: setAlias }
               ## WOULD NEED URL FROM LDAP OR BASE64 capabilites:  - { ldap_attr: jpegphoto, user_method: setAvatar }

        role:
            baseDn: cn=groups,dc=somedomain,dc=de
            filter: (&(| (cn=users)(cn=teamlead)(cn=kimai_admin)(cn=operators)))
            usernameAttribute: memberuid
            nameAttribute: cn
            userDnAttribute: uniquemember
            groups:
                 - { ldap_value: teamlead, role: ROLE_TEAMLEAD }
                 - { ldap_value: kimai_admin, role: ROLE_ADMIN }
                 - { ldap_value: operators, role: ROLE_ADMIN }
                 - { ldap_value: users, role: ROLE_USER }
```
