### ISSUE TITLE
Search field hides the set of buttons next to it.

### ISSUE THREAD

**Issue by bpjobin** [kevinpapst/kimai2#2562]
**Describe the bug**
Search field hides the set of buttons next to it.

**Desktop (please complete the following information):**
 - Docker version: 18.09.8
 - Docker compose version: 1.24.0, build 0aa59064

```
version: '3.5'
services:
  nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    ports:
      - 8001:80
    volumes:
      - public:/opt/kimai/public:ro
    restart: unless-stopped
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
        - REDACTED

  kimai:
    image: kimai/kimai2:latest
    environment:
      - ADMINMAIL=REDACTED
      - ADMINPASS=REDACTED
      - DATABASE_URL=mysql://kimai:REDACTED@REDACTED:3307/kimai
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1,REDACTED
    volumes:
      - public:/opt/kimai/public
    networks:
        - REDACTED

networks: 
    REDACTED:
        external: true

volumes:
    public:
```

**Additional context**
Problem occurs on Safari and Chrome and on every pages.

![Screen Shot 2021-05-10 at 6 53 22 AM](https://user-images.githubusercontent.com/46512567/117648626-7308db80-b15c-11eb-9989-e7007712fef2.png)

![Screen Shot 2021-05-10 at 6 52 26 AM](https://user-images.githubusercontent.com/46512567/117648559-5e2c4800-b15c-11eb-9c5c-0389b0009232.png)
