### ISSUE TITLE
Support Kimai behind httpd basic auth

### ISSUE THREAD

**Issue by Al2Klimov** [kevinpapst/kimai2#3046]
**Is your feature request related to a problem? Please describe.**
I put everything I can behind httpd basic auth (LDAP backend). Even if I connect Kimai to the same LDAP, users would have to enter their credentials twice.

**Describe the solution you'd like**
1. Choose between the below bullet points.
2. Show me the code location where to start the implementation.

**Describe alternatives you've considered**
* Kimai automatically recognizes the HTTP basic auth header and tries those credentials before redirecting to login page
* Kimai automatically recognizes the REMOTE_USER env var and auto-creates that user

**Screenshot**
Add a mockup / screenshot of your idea here.

**Comment by kevinpapst** [comment]
I have no clue, as I never tried it.
Please start reading here: https://symfony.com/doc/4.4/security/auth_providers.html

**Comment by Al2Klimov** [comment]
And you don’t even have a preference which of the two mentioned features you'd like to be implemented?

**Comment by kevinpapst** [comment]
I'd prefer if you give it a try and share your experience. 
I never used this kind of authentication and find it hard to decide which one is better suited and easier to implement with Kimai. Maybe it is only a matter of configuration, then all we need is a documentation page.

**Comment by Al2Klimov** [comment]
Kimai + LDAP along with

```patch
diff --git a/config/packages/security.yaml b/config/packages/security.yaml
index a192b691..b02d9c64 100644
--- a/config/packages/security.yaml
+++ b/config/packages/security.yaml
@@ -17,6 +17,8 @@ security:
             security: false

         secured_area:
+            http_basic:
+                    realm: LDAP
             kimai_saml: ~
             kimai_ldap: ~
             pattern: ^/
```

seems to work.

**Comment by kevinpapst** [comment]
Wow, it was really so easy? Users are created on the fly?

**Comment by kevinpapst** [comment]
Can you share a little bit about that setup? How are users created? Is your username the email address?
Does group sync work in that setup? Do you still have the Kimai LDAP activated?

**Comment by Al2Klimov** [comment]
Damn. At least if $USER didn’t log in before that config:

![Bildschirmfoto 2021-12-31 um 15 48 12](https://user-images.githubusercontent.com/6053266/147829170-c1590a41-7e21-4745-82c5-dd408a7d91d8.png)

**Comment by kevinpapst** [comment]
So not completely done yet. That screens says nothing. Check log files in var/log

**Comment by Al2Klimov** [comment]
OK, the following **LDAP+REMOTE_USER** doesn’t make any sense... but it seems to work:

```yaml
---
- name: apt install *
  loop:
    - libapache2-mod-php7.4
    - php7.4-gd
    - php7.4-intl
    - php7.4-json
    - php7.4-ldap
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-xml
    - php7.4-zip
    - composer
    - python3-mysqldb
  package:
    name: '{{ item }}'

- name: CREATE DATABASE kimai
  mysql_db:
    name: kimai
- name: GRANT ALL ON kimai.*
  mysql_user:
    name: kimai
    password: |-
      {{ lookup('password', '../../cache/alpha/root/.kimai-dbpw') }}
    priv: 'kimai.*:ALL'

- name: /var/www/kimai
  git:
    dest: /var/www/kimai
    repo: https://github.com/kevinpapst/kimai2.git
    version: 3621b8c27c57539fbfbf8605ddc111c1385fa576
    force: yes

- name: composer install -d /var/www/kimai
  composer:
    working_dir: /var/www/kimai

- name: composer require -d /var/www/kimai laminas/laminas-ldap
  composer:
    working_dir: /var/www/kimai
    command: require
    arguments: laminas/laminas-ldap

- name: /var/www/kimai/.env
  copy:
    dest: /var/www/kimai/.env
    content: |
      DATABASE_URL=mysql://kimai:{{
        lookup('password', '../../cache/alpha/root/.kimai-dbpw')
      }}@127.0.0.1:3306/kimai?charset=utf8&serverVersion=10.3.32
      MAILER_FROM=info@manufaktura-elfov.org
      MAILER_URL=smtp://localhost:25?encryption=&auth_mode=
      APP_ENV=prod
      APP_SECRET={{ lookup('password', '../../cache/alpha/root/.kimai-saltpw') }}
      CORS_ALLOW_ORIGIN=^https?://localhost(:[0-9]+)?$
      TRUSTED_HOSTS=time.manufaktura-elfov.org

- name: bin/console kimai:install -n
  shell: |
    set -e
    bin/console kimai:install -n
    touch /var/www/kimai/.moe-installed
  args:
    chdir: /var/www/kimai
    creates: /var/www/kimai/.moe-installed

- name: /var/www/kimai/config/packages/local.yaml
  copy:
    dest: /var/www/kimai/config/packages/local.yaml
    content: |
      kimai:
        ldap:
          activate: true
          connection:
            host: 127.0.0.1
            username: cn=bot,dc=manufaktura-elfov,dc=org
            password: |-
              {{ lookup('password', '../../cache/alpha/root/.ldap-botpw') }}
            accountFilterFormat: (cn=%s)
          user:
            baseDn: dc=manufaktura-elfov,dc=org
            usernameAttribute: cn

- name: '/var/www/kimai/config/packages/security.yaml: REMOTE_USER'
  blockinfile:
    path: /var/www/kimai/config/packages/security.yaml
    insertafter: secured_area
    marker: '# {mark} REMOTE_USER'
    block: '            remote_user: {provider: kimai_ldap}'

- name: rm -rf /var/www/kimai/var/cache/prod
  file:
    path: /var/www/kimai/var/cache/prod
    state: absent

- name: chown -R :www-data /var/www/kimai
  file:
    path: /var/www/kimai
    recurse: yes
    group: www-data
    mode: g+r
- name: chmod -R g+w /var/www/kimai/var
  file:
    path: /var/www/kimai/var
    recurse: yes
    mode: g+w
- name: chmod -R g+w /var/www/kimai/public/avatars
  file:
    path: /var/www/kimai/public/avatars
    recurse: yes
    mode: g+w

- name: /etc/apache2/sites-available/kimai.conf
  copy:
    dest: /etc/apache2/sites-available/kimai.conf
    src: ../files/vhosts/kimai.conf

- name: /etc/apache2/sites-enabled/kimai.conf
  file:
    path: /etc/apache2/sites-enabled/kimai.conf
    state: link
    src: ../sites-available/kimai.conf
```
