### ISSUE TITLE
SAML Auth - Error 500

### ISSUE THREAD

**Issue by hexxone** [kevinpapst/kimai2#3211]
**Describe the bug**
I am trying to set up SAML Auth with [Authentik](https://goauthentik.io/) according to the docs, but keep getting
` Error 500: Internal Server Error Description: The server met an unexpected condition`
on  the endpoint `/auth/saml/acs`.

Sadly the logs don't seem to hint at anything specific...

**To Reproduce**
1. Follow the [SAML set-up steps](https://www.kimai.org/documentation/saml.html)
2. Mount the config, restart container
3. Click on 'Login with SAML'

**Logfile**

Seems useless tbh. Nothing logged regarding SAML even though "debug" is enabled.
```
[Mon Mar 21 06:07:46.102947 2022] [mpm_prefork:notice] [pid 87] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Mon Mar 21 06:07:46.102969 2022] [core:notice] [pid 87] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes) in /opt/kimai/var/cache/de_/twig/f2/f22ba59339c73152b621c2d3250dbde11a07f35013dc433494a859844db5e09d.php on line 279
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/vendor/symfony/var-dumper/Caster/ExceptionCaster.php on line 202
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /opt/kimai/vendor/twig/twig/src/ExpressionParser.php on line 633
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/vendor/symfony/var-dumper/Caster/ExceptionCaster.php on line 338
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 61440 bytes) in /opt/kimai/vendor/twig/twig/src/Compiler.php on line 112
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/vendor/symfony/var-dumper/Cloner/Data.php on line 340
[Mon Mar 21 10:16:34.708295 2022] [core:warn] [pid 60] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
....

localhost:8001 127.0.0.1 - - [21/Mar/2022:10:16:46 +0100] "GET / HTTP/1.1" 302 1189 "-" "curl/7.64.0"
localhost:8001 192.168.208.8 - - [21/Mar/2022:10:16:53 +0100] "GET / HTTP/1.1" 302 1308 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
localhost:8001 192.168.208.8 - - [21/Mar/2022:10:16:53 +0100] "GET /de/homepage HTTP/1.1" 302 1323 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
localhost:8001 192.168.208.8 - - [21/Mar/2022:10:16:53 +0100] "GET /de/login HTTP/1.1" 200 11588 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
localhost:8001 192.168.208.8 - - [21/Mar/2022:10:16:54 +0100] "GET /favicon.ico HTTP/1.1" 304 125 "https://time.mycompany.com/de/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
localhost:8001 192.168.208.8 - - [21/Mar/2022:10:16:55 +0100] "GET /auth/saml/login HTTP/1.1" 302 1044 "https://time.mycompany.com/de/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
localhost:8001 192.168.208.8 - - [21/Mar/2022:10:16:58 +0100] "GET /auth/saml/acs?SAMLResponse=xVhZj6O61n3PryhVP0bdzAFKp1sfQ0hIgARIQpKXK8BmCDNmSPLrL6npdNXpqtvnflc6UkkVb%2B%2B9vby8jb38B3KztHywICqLHMG7c5bm6OHR%2BP2%2BrfOHwkUxesjdDKKHxn%2BwBV17IL%2FhD2VdNIVfpPc%2FhXwe4SIE6yYu8pcQgL7fR01TPmBY3%2FffeupbUYcYieM4hvPY4ANQHH558c7A5%2Bkz2LjAbdz7ux2s0TDM9%2FvBfH%2BnItRCNUeNmzeDCSfJrzj1lSQ2OP9ATB4Y9nh%2FJ0PUW5%2F%2FHHbciHx6nUPz4F%2BAf2s%2BsfT8trN27TorctqQDwbuemLfycV%2FTo%2FWC3vg8Rusd%2BPI3wNumD8LK479m%2FEcRyLsmwBOB8l6a5CcVzHg09jnd9niF9Gv7WIv33HIABfRwOy9vW8MfopQwg1CvOnpQnvvcjk5vvK0n0Anmusx1kvWPcSaODrnniFvfPzJJjSU0BBA18j0WxpnVRUvUiq1xYlg6ulHqucZvYBizwVkDcJJQEhmvKyGl5ATfLtiU6z5F42miNNBuO5QO4ZhKr25vO2aNZmh%2F2UnySgHkoyQ3h45t5%2BP3pZHx%2F1I1erc%2FHIfbmqHxzmD6rGLv1TtBvnlvGILpU%2VxP%2F6EvCIYoDawHPzC5OUuggNcu3Hp29S%2FoN%2F8xvM6%2BFfX9RgXRfNsKQQPArSsqibV8J%2BkfwXfW9sr6S9IGwGsr22gR923N024KvMRX4EMxd9C4tbcQ7ucfItLgbJSw6Sl3wq1jYG9%2B%2BzPF3aCeIFy1v7e%2BvvYRj0NSrc8lFz9%2Bgmuxls%2BIvBDVZzwQYm4wxhN5Y%2FwCMXWZzH%2Ft0mimEK%2F5fYPuUHwfoTUOAJVPM%2Fx%2FSbfLVl%2FjvI%2Fu%2Fdvv4HkA6%2BceoCUN8eAv9hyFns1wUqgubxG%2FcEmsPwyV9A93EOih65vl%2B0efNP18EzqFldtOUHOPLhG%2BKnRQvutkPhog%2BQ%2FMr4ugXuBDDM5e%2BE%2Fjno3w4NB0njev9FXO0Gbu5%2BHvgXwt8ZfvqMYm8fol%2FfqV8uGD%2F%2BDQ%3D%3D&RelayState=http%3A%2F%2Ftime.mycompany.com%3A8001%2Fauth%2Fsaml%2Flogin HTTP/1.1" 500 238605 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
localhost:8001 127.0.0.1 - - [21/Mar/2022:10:17:06 +0100] "GET / HTTP/1.1" 302 1189 "-" "curl/7.64.0"
localhost:8001 127.0.0.1 - - [21/Mar/2022:10:17:27 +0100] "GET / HTTP/1.1" 302 1189 "-" "curl/7.64.0"

```
(I shortened the string SAMLResponse a little bit.)

**Additional context**

docker-compose
```
  timetrack:
    hostname: timetrack
    container_name: timetrack
    image: kimai/kimai2:apache-latest
    restart: unless-stopped
    networks:
      - tt_net
      - web
    depends_on:
      - timetrack_db
    environment:
      APP_ENV: dev
      ADMINMAIL: admin@mycompany.com
      ADMINPASS: kimaih7n
      DATABASE_URL: mysql://root:BLABLABLA@timetrack_db/kimai
      TRUSTED_HOSTS: nginx,localhost,127.0.0.1,traefik,192.168.208.9,time.mycompany.com
    labels:
      traefik.enable: true
      # HTTP -> HTTPS
      traefik.http.routers.timetrack-redirect.entrypoints: web
      traefik.http.routers.timetrack-redirect.rule: Host(`time.${HOST}`)
      traefik.http.routers.timetrack-redirect.middlewares: httpsredirect@docker
      # HTTPS -> Entry router
      traefik.http.routers.timetrack.entrypoints: websecure
      traefik.http.routers.timetrack.rule: Host(`time.${HOST}`)
      # traefik.http.routers.timetrack.tls: true
      traefik.http.routers.timetrack.tls.certresolver: cfresolver
      traefik.http.routers.timetrack.middlewares: limit@docker,error-pages@docker
      traefik.http.routers.timetrack.service: timetrack
      # Entry
      traefik.http.services.timetrack.loadbalancer.server.port: 8001
      # traefik.http.services.timetrack.loadbalancer.server.scheme: http
      traefik.http.services.timetrack.loadbalancer.passHostHeader: true
    volumes:
      - ./kimai/local.yaml:/opt/kimai/config/packages/local.yaml

```
