### ISSUE TITLE
Profile page in error 503 when user have @ in username (due to SAML)

### ISSUE THREAD

**Issue by simone-gasparini** [kevinpapst/kimai2#3288]
**Describe the bug**
Profile page goes in error 503 when username have an @ (username is an email due to SAML authentication).
Investigating on it, I've noticed that in dev run without any problem, in prod run only the first time, so it goes in error 503.
I think that this error must have a relation with the cache system that does not like the @ character in the url: https://kimai.xxxx.xxx/it/profile/name@xxxx.xx

**To Reproduce**
1. Environment in prod
2. Create a user with email in username
3. Go to profile page
4. Refresh page

**Logfile**
No log available

**Additional context**
 - Kimai version: 1.19.6
 - PHP version: 7.4.29
 - Device: Any
 - Browser: Any

**Comment by simone-gasparini** [comment]
The problem is related with doctrine query and result cache.
Commenting the doctrine.yaml file like this, all works fine.
```
doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: doctrine.system_cache_provider
#        query_cache_driver:
#            type: service
#            id: doctrine.system_cache_provider
#        result_cache_driver:
#            type: service
#            id: doctrine.result_cache_provider
```
