### ISSUE TITLE
SAML2 Authentik Error sp_not_found, idp_not_found

### ISSUE THREAD

**Issue by incoggnito** [kevinpapst/kimai2#3418]
**Describe the bug**

The https://kimai.company login without SAML2 works pretty well with a docker-compose setup. But the SAML configuration throws an error:

> NOTICE: PHP message: [2022-07-16 09:17:41] request.CRITICAL: Uncaught PHP Exception OneLogin\Saml2\Error: "Invalid array settings: sp_not_found, idp_not_found" at /opt/kimai/vendor/onelogin/php-saml/src/Saml2/Settings.php line 141 {"exception":"[object] (OneLogin\\Saml2\\Error(code: 2): Invalid array settings: sp_not_found, idp_not_found at /opt/kimai/vendor/onelogin/php-saml/src/Saml2/Settings.php:141)"} []

**To Reproduce**
1. Go to https://kimai.company/auth/saml/acs
2. Error Something is wrong
3. See log error in container

**Additional context**
- docker-compose

  ```
  version: '3.5'
  services:
  
    sqldb:
      image: mysql:5.7
      environment:
        - MYSQL_DATABASE=kimai
        - MYSQL_USER=kimaiuser
        - MYSQL_PASSWORD=passw
        - MYSQL_ROOT_PASSWORD=hardpassw
      volumes:
        - mysql:/var/lib/mysql
      command: --default-storage-engine innodb
      restart: unless-stopped
      healthcheck:
        test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
        interval: 20s
        start_period: 10s
        timeout: 10s
        retries: 3
  
    nginx:
      image: tobybatch/nginx-fpm-reverse-proxy
      ports:
              - 8002:80
      volumes:
        - public:/opt/kimai/public:ro
      restart: unless-stopped
      depends_on:
        - kimai
      healthcheck:
        test:  wget --spider http://nginx/health || exit 1
        interval: 20s
        start_period: 10s
        timeout: 10s
        retries: 3
  
    kimai: # This is the latest FPM image of kimai
      image: kimai/kimai2:fpm
      environment:
        - ADMINMAIL=admin@mail.de
        - ADMINPASS=hardpassw
        - DATABASE_URL=mysql://kimaiuser:passw/kimai
        - TRUSTED_HOSTS=nginx,localhost,127.0.0.1,192.168.105.108,kimai.company                                                                                                                          
      volumes:
        - public:/opt/kimai/public
        - ./config:/opt/kimai/config/packages
      restart: unless-stopped
  
    postfix:
      image: catatnight/postfix:latest
      environment:
        maildomain: mail.de
        smtp_user: kimai:kimai
      restart: unless-stopped
  
  volumes:
      var:
      public:
      mysql:
   ```
  

- SAML2 config: https://goauthentik.io/integrations/services/kimai/
 - Kimai version: Latest
 - PHP version: ?
 - Device: Windows 10
 - Browser Brave

I guess the service provider and the identity provider is not found. Any ideas what could be the reason?
