### ISSUE TITLE
 Weekly working hours and rounding

### ISSUE THREAD

**Issue by schmunk42** [kevinpapst/kimai2#3604]
### Describe the issue

We've rounding to 15 minutes enabled.

```
kimai:
  timesheet:
    rounding:
      default:
        begin: 15
        end: 15
```

When using  **Weekly working hours** in any other minute than 0,15,30 or 45. 15 minutes get added to the entered time.

---

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kevinpapst/kimai2/discussions).

### Kimai version

1.27.0+api-firewall

### Which PHP version are you using?

7.4

### How do you run Kimai?

Self-Hosted

### Steps to reproduce the behavior

1. go to weekly view
2. enter new values

![Bildschirmfoto vom 2022-10-27 15-21-19](https://user-images.githubusercontent.com/649031/198296320-72ea4c7d-29ae-4066-834e-d4aed23218a0.png)

3. click save

4. see 15 minutes added
![Bildschirmfoto vom 2022-10-27 15-21-29](https://user-images.githubusercontent.com/649031/198296451-3cfc1601-9785-4802-9b9a-1d38ac5d1a3f.png)

editing of existing times works fine, since they are already rounded

**Comment by kevinpapst** [comment]
Change your default time in System configuration from `now` to `10:00:00`?

**Comment by kevinpapst** [comment]
Besides the last answer you might want to round duration to 15 or 30 minutes and not begin and end.

**Comment by schmunk42** [comment]
I currently have this:
```
  timesheet:
    rounding:
      default:
        begin: 15
        end: 15
```

But you mean I should do it like so?
```
    timesheet:
        # Rounding rules are used to round the begin & end dates and the duration for timesheet records.
        # The "default" rule will round "begin" down and "end" up to the full minute, the "duration" will not be rounded.
        rounding:
           default:             
               duration: 15
```
