### ISSUE TITLE
API docs are wrong for GET entity (ignores serialization group)

### ISSUE THREAD

**Issue by hmr-it-jr** [kevinpapst/kimai2#701]
**Is your feature request related to a problem? Please describe.**
The documentation says /api/activities returns:
```
[
  {
    "id": 0,
    "name": "string",
    "comment": "string",
    "visible": true,
    "fixed_rate": 0,
    "hourly_rate": 0,
    "project": 0
  }
]
```

but actually it returns:
```
[
    {
        "id": 3,
        "name": "act 4 customer 1",
        "visible": true
    },
    {
        "id": 1,
        "name": "develop",
        "visible": true
    },
    {
        "id": 2,
        "name": "test",
        "visible": true
    }
]
```
the fields: "comment", "fixed_rate", "hourly_rate", "project" are missing.

----------------------

expedted output from /api/customers
```
[
  {
    "id": 0,
    "name": "string",
    "number": "string",
    "comment": "string",
    "visible": true,
    "company": "string",
    "contact": "string",
    "address": "string",
    "country": "string",
    "currency": "string",
    "phone": "string",
    "fax": "string",
    "mobile": "string",
    "email": "string",
    "homepage": "string",
    "timezone": "string",
    "fixed_rate": 0,
    "hourly_rate": 0
  }
]
```

output I get:
```
[
    {
        "id": 1,
        "name": "Customer 1",
        "visible": true
    },
    {
        "id": 2,
        "name": "Customer 2",
        "visible": true
    },
    {
        "id": 3,
        "name": "Customer 3",
        "visible": true
    }
]
```
--------
expected output from /api/projects
```
[
  {
    "id": 0,
    "name": "string",
    "comment": "string",
    "visible": true,
    "budget": 0,
    "order_number": "string",
    "fixed_rate": 0,
    "hourly_rate": 0,
    "customer": 0
  }
]
```

output I get:
```
[
    {
        "id": 1,
        "name": "prj 4 cus 1",
        "visible": true,
        "customer": 1
    },
    {
        "id": 2,
        "name": "prj 4 cus 2",
        "visible": true,
        "customer": 2
    },
    {
        "id": 4,
        "name": "prj 4 cus 3",
        "visible": true,
        "customer": 3
    },
    {
        "id": 3,
        "name": "prj 41 cus 1",
        "visible": true,
        "customer": 1
    }
]
```

**Describe the solution you'd like**
Please add the missing fields the way they are described in the documentation, because I need to know for the Kimai 2 app which activities are global activities and which are activities allocated to a project.

**Comment by kevinpapst** [comment]
Hm, I still don't know if that is a "bug" in the API documentation module or me being too stupid to configure it properly. I guess the latter one... you are right, the output is different from the docu, BUT:
the behavior is not a bug but intended. 

The collection calls return a limited data-set as configured e.g. for Activity:
https://github.com/kevinpapst/kimai2/blob/master/config/serializer/App/Entity.Activity.yml
There are different serialization groups: `Entity` (only returned for an explicit GET on the ID), `Collection` (included in the GETs for the entire collection) and `Default` (included in both result sets).

The master includes the `project` field in the activities collection, which is the identifier you need to check. If it is missing, the activity is global.

If you need some changes in the collection results, please open a PR with the config changes (in [this directory](https://github.com/kevinpapst/kimai2/tree/master/config/serializer/App)). Be aware: there is come aggressive caching going on in the API libraries. If config changes won't load, don't use the `cache:clear` command, but delete the entire cache directory `rm -rf var/cache/*`.

I'll leave this open to fix the documentation.

**Comment by hmr-it-jr** [comment]
So do I understand you correctly? - with setting groups to [Default] it should be included in both result sets?

I don't think it is like this, because at the moment my Entitiy.Activity.yml looks like this
```
App\Entity\Activity:
    exclusion_policy: All
    custom_accessor_order: [id, name, comment, visible, project, fixedRate, hourlyRate]
    properties:
        id:
            include: true
            groups: [Default]
        name:
            include: true
            groups: [Default]
        comment:
            include: true
            groups: [Entity]
        visible:
            include: true
            groups: [Default]
        fixedRate:
            include: true
            groups: [Default]
        hourlyRate:
            include: true
            groups: [Default]
        project:
            include: false
            exclude: true
            groups: [Default]
    virtual_properties:
        getProject:
            serialized_name: project
            exp: "object.getProject() === null ? null : object.getProject().getId()"
            type: integer
            groups: [Default]

```
And the fields are not showing as expected. So this is the config which I use now: everything set to Collection and project include/exclude changed:
```
App\Entity\Activity:
    exclusion_policy: All
    custom_accessor_order: [id, name, comment, visible, project, fixedRate, hourlyRate]
    properties:
        id:
            include: true
            groups: [Collection]
        name:
            include: true
            groups: [Collection]
        comment:
            include: true
            groups: [Collection]
        visible:
            include: true
            groups: [Collection]
        fixedRate:
            include: true
            groups: [Collection]
        hourlyRate:
            include: true
            groups: [Collection]
        project:
            include: true
            exclude: false
            groups: [Collection]
    virtual_properties:
        getProject:
            serialized_name: project
            exp: "object.getProject() === null ? null : object.getProject().getId()"
            type: integer
            groups: [Collection]
```
I deleted and recreated the cache folder, warmed up cache again with 
```
 php bin/console cache:warmup --env=prod
```
but the output is the same:
```
[
    {
        "id": 3,
        "name": "act 4 customer 1",
        "visible": true
    },
    {
        "id": 1,
        "name": "develop",
        "visible": true
    },
    {
        "id": 2,
        "name": "test",
        "visible": true
    }
]
```
